services:
  postgres:
    image: postgres:16
    container_name: pulse_postgres
    environment:
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse_secret
      POSTGRES_DB: pulse_protocol
      POSTGRES_INITDB_ARGS: "--locale=C.UTF-8 --encoding=UTF8"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pulse_pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse -d pulse_protocol"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pulse_redis
    ports:
      - "6379:6379"
    volumes:
      - pulse_redisdata:/data
    command: redis-server --appendonly yes

volumes:
  pulse_pgdata:
  pulse_redisdata: